<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="InputDenda" targetNamespace="http://xmlns.oracle.com/Application1/Denda/InputDenda" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/Application1/Denda/InputDenda" xmlns:ns1="http://www.example.org" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.example.org" schemaLocation="xsd/InputDenda.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="InputDendaRequestMessage">
      <wsdl:part name="payload" element="ns1:Request"/>
   </wsdl:message>
   <wsdl:message name="InputDendaResponseMessage">
      <wsdl:part name="payload" element="ns1:Response"/>
   </wsdl:message>
   <wsdl:portType name="InputDenda">
      <wsdl:operation name="process">
         <wsdl:input message="client:InputDendaRequestMessage"/>
         <wsdl:output message="client:InputDendaResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="InputDenda">
      <plnk:role name="InputDendaProvider" portType="client:InputDenda"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
