<?binding.jca getTindakan_db.jca?>
<wsdl:definitions name="getTindakan" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/pcareTindakan/pcareTindakan/getTindakan" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/getTindakan" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/pcareTindakan/pcareTindakan/getTindakan" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="getTindakan_plt">
        <plt:role name="getTindakan_role">
            <plt:portType name="tns:getTindakan_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getTindakan" schemaLocation="xsd/getTindakan.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="getTindakanInput_msg">
        <wsdl:part name="getTindakanInput_msg" element="db:getTindakanInput"/>
    </wsdl:message>
    <wsdl:message name="getTindakanOutputCollection_msg">
        <wsdl:part name="getTindakanOutputCollection" element="db:getTindakanOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="getTindakan_ptt">
        <wsdl:operation name="getTindakan">
            <wsdl:input message="tns:getTindakanInput_msg"/>
            <wsdl:output message="tns:getTindakanOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
